#!/bin/bash
fetchmail                      # gets the emails, extracts the PDFs to ~/attachments
wait "$!"                      # takes some time so I have to wait for it to finish
shopt -s nullglob              # don't present pattern if no files are matched
FILES=(/home/pi/HotlabConnect/pdf2Print/*)
for f in "${FILES[@]}"; do                              # go through all files in the directory
    [[ $f == *.pdf ]] && lpr "$f"  # print them if they're PDFs
done
sudo rm -- "${FILES[@]}" /home/pi/HotlabConnect/pdf2Print        # delete files and emails at once