#! /bin/sh
# /etc/init.d/HotlabBroker

### BEGIN INIT INFO
# Provides:          HotlabConnect
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HotlabConnect
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
   start)
    echo "Starting index.js"
    # run application you want to start
    #node /home/pi/HotlabBroker/index.js > /home/pi/HotlabBroker/HotlabBroker.log
    /usr/local/bin/node /home/pi/HotlabConnect/index.js >> /home/pi/HotlabConnect/HotlabConnect.log
   ;;
   stop)
    echo "Stopping index.js"
    # kill application you want to stop
    killall -9 node
    # Not a great approach for running
    # multiple node instances
    ;;
  *)
    echo "Usage: /etc/init.d/HotlabBroker {start|stop}"
    exit 1
    ;;
esac

exit 0
